### ISSUE TITLE
Update to (support) Stata 13, 14, 15

### ISSUE THREAD

**Issue by briatte** [briatte/srqm#12]
The course was originally written for Stata 10/11, and has been tested with Stata 12, but not Stata 13.

**Comment by briatte** [comment]
Stata 13 supports UTF-8 – and breaks the data format from previous versions. Updating to Stata 13 would make the course incompatible with many teaching sites, so not updating is actually better.

**Comment by dinosv** [comment]
Same thing with Stata 14.0; it breaks importing from .csv and generate different datasets :(

**Comment by briatte** [comment]
Reopening to take Stata 15 into account, and to give another try at fixing the multiple Stata data formats. Objective is to support Stata 12+.

**Comment by briatte** [comment]
Closed by #28.
