### ISSUE TITLE
License? And Jupyter notebook example

### ISSUE THREAD

**Issue by kylebarron** [briatte/srqm#20]
Hello! I was just perusing Stata-related github repositories and came across this. There's no license file, so I wasn't sure if the content was openly-licensed. By default, repositories without a license file [have all rights reserved](https://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github). 

Secondly, I've been working on a [Jupyter kernel for Stata](https://kylebarron.github.io/stata_kernel/), which allows Stata to be run directly from Jupyter Notebooks. I'd been wanting to make an example notebook anyways, so I converted the `week2.do` file into a Jupyter Notebook. It's nice because Github includes the output and graphs when it displays Jupyter Notebook files.

If you click here: https://github.com/kylebarron/srqm/blob/master/code/week2.ipynb you'll see all the output of the `week2.do` file rendered next to the Markdown descriptions.

![image](https://user-images.githubusercontent.com/15164633/45256922-5db7cf80-b36b-11e8-8ead-6804b4a7055e.png)

**Comment by briatte** [comment]
Hi, and thanks for your question -- I'll CC-BY-SA the repo on the next update.

The Jupyter notebook looks awesome!

**Comment by briatte** [comment]
Hi @kylebarron — I'm closing this issue since the repo README now has [a LICENSE section](https://github.com/briatte/srqm#license). Congrats again for your work on the Jupyter kernel for Stata, the Atom demo video is truly impressive.
